# Generated by Django 5.1.2 on 2024-10-14 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile_app', '0003_alter_userprofile_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habbits_Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(max_length=100)),
                ('movie', models.CharField(max_length=100)),
                ('books', models.CharField(max_length=100)),
                ('travel', models.CharField(max_length=100)),
                ('volunteer_work', models.CharField(max_length=100)),
                ('cooking', models.CharField(max_length=100)),
                ('music', models.CharField(max_length=100)),
                ('writing', models.CharField(max_length=100)),
                ('gaming', models.CharField(max_length=100)),
                ('gardening', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserProfile_app.userprofile')),
            ],
        ),
    ]
