# Generated by Django 5.1.2 on 2024-10-14 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile_app', '0003_alter_userprofile_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_for', models.CharField(choices=[('My parents will stay with me after marriage', 'My parents will stay with me after marriage'), ('My parents will not stay with me after marriage', 'My parents will not stay with me after marriage'), ('Dont wish to specify', 'Dont wish to specify')], max_length=50)),
                ('family_values', models.CharField(max_length=100)),
                ('family_type', models.CharField(max_length=100)),
                ('family_status', models.CharField(max_length=100)),
                ('no_of_brothers', models.IntegerField()),
                ('no_of_brothers_married', models.IntegerField()),
                ('no_of_sisters', models.IntegerField()),
                ('no_of_sisters_married', models.IntegerField()),
                ('mother_tongue', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('family_wealth', models.CharField(max_length=100)),
                ('about_family', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserProfile_app.userprofile')),
            ],
        ),
    ]
