# Generated by Django 5.1.2 on 2024-10-14 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('height', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('zipcode', models.CharField(max_length=10)),
                ('profile_created_by', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('income', models.FloatField()),
                ('religion', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=100)),
                ('subcaste', models.CharField(max_length=100)),
                ('about_yourself', models.TextField()),
                ('image', models.ImageField(upload_to='media/profile_images/')),
            ],
        ),
    ]
