# Generated by Django 5.1.2 on 2024-10-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile_app', '0003_alter_userprofile_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPreferenceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_for', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=20)),
                ('age_from', models.IntegerField()),
                ('age_to', models.IntegerField()),
                ('height_from', models.DecimalField(decimal_places=2, max_digits=4)),
                ('height_to', models.DecimalField(decimal_places=2, max_digits=4)),
                ('religion', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('complexion', models.CharField(max_length=50)),
                ('residency_status', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('partner_expectations', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserProfile_app.userprofile')),
            ],
        ),
    ]
