# Generated by Django 5.1.2 on 2024-10-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoroscopeDetails_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscopedetails',
            name='horoscope_match',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='horoscopedetails',
            name='manglik',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='horoscopedetails',
            name='shani',
            field=models.BooleanField(),
        ),
    ]
