# Generated by Django 5.1.2 on 2024-10-14 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile_app', '0003_alter_userprofile_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternative_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('convenient_time_to_call', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('permanent_address', models.TextField()),
                ('working_address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserProfile_app.userprofile')),
            ],
        ),
    ]
